import { AnimatePresence, motion } from "framer-motion";
import { BookOpen, CalendarDays, CheckCircle2, Clock3, ListChecks } from "lucide-react";
import { useState } from "react";
import { useSearchParams } from "react-router-dom";
import { toast } from "sonner";
import { ChatHeader } from "@/components/chat/chat-header";
import { MessageComposer } from "@/components/chat/message-composer";
import { MessageList } from "@/components/chat/message-list";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent } from "@/components/ui/dialog";
import { useAssignments, useSubmission, useSubmitHomework } from "@/modules/homework";
import { useLessons } from "@/modules/lesson";
import { LiveLessonDialog } from "@/modules/live";

const tabs = [{ id: "chat", label: "Chat", icon: BookOpen }, { id: "lessons", label: "Darslar", icon: CalendarDays }, { id: "assignments", label: "Vazifalar", icon: ListChecks }];
export function StudentGroupWorkspace({ conversation, messages, sendMessage, sendTyping, retryMessage, currentUserId }) {
  const [params, setParams] = useSearchParams(); const [reply, setReply] = useState(null); const courseId = conversation.courseId; const lessons = useLessons({ course: courseId, page_size: 100 }); const assignments = useAssignments(courseId); const active = tabs.some((item) => item.id === params.get("tab")) ? params.get("tab") : "chat";
  async function send(payload) { try { await sendMessage.mutateAsync({ ...payload, replyTo: reply ? { author: reply.senderName || "Javob", text: reply.text } : undefined }); setReply(null); } catch { toast.error("Xabar yuborilmadi"); } }
  return <section className="chat-page group-workspace student-group-workspace"><ChatHeader conversation={conversation} backTo="/student/chats" /><nav className="group-tabs">{tabs.map((tab) => { const Icon = tab.icon; return <button key={tab.id} className={active === tab.id ? "is-active" : ""} onClick={() => setParams(tab.id === "chat" ? {} : { tab: tab.id })}>{active === tab.id ? <motion.span layoutId="student-group-tab" className="group-tab-indicator" /> : null}<Icon size={16} />{tab.label}</button>; })}</nav><AnimatePresence mode="wait"><motion.div key={active} className="group-tab-content" initial={{ opacity: 0, y: 5 }} animate={{ opacity: 1, y: 0 }}>{active === "chat" ? <MessageList messages={messages.data} conversation={conversation} loading={messages.isLoading} error={messages.isError} onRetry={messages.refetch} onRetryMessage={retryMessage} currentUserId={currentUserId} onReply={setReply} onEdit={() => undefined} onDelete={() => undefined} onReact={() => undefined} capabilities={{ reply: true, edit: false, delete: false, react: false }} /> : null}{active === "lessons" ? <StudentLessons lessons={lessons.data} loading={lessons.isLoading} /> : null}{active === "assignments" ? <StudentAssignments assignments={assignments.data} loading={assignments.isLoading} /> : null}</motion.div></AnimatePresence>{active === "chat" ? <MessageComposer onSend={send} onTyping={sendTyping} sending={sendMessage.isPending} replyTo={reply} currentUserId={currentUserId} onCancelContext={() => setReply(null)} /> : null}</section>;
}
function StudentLessons({ lessons = [], loading }) { const [live, setLive] = useState(null); if (loading) return <div className="student-tab-loading"><span /></div>; return <div className="group-panel student-readonly-panel"><div className="group-panel-head"><div><span>KURS DARSLARI</span><h2>Darslar</h2></div></div><div className="student-workspace-list">{lessons.map((lesson) => <article key={lesson.id}><span className="workspace-list-icon"><CalendarDays size={20} /></span><div><strong>{lesson.title}</strong><p>{lesson.date} · {lesson.time} · <Clock3 size={14} /> {lesson.durationMinutes} daqiqa</p></div><Button size="sm" disabled={["finished", "cancelled"].includes(lesson.status)} onClick={() => setLive(lesson)}>Darsga kirish</Button></article>)}</div><LiveLessonDialog lesson={live} open={Boolean(live)} onOpenChange={(open) => { if (!open) setLive(null); }} /></div>; }
function StudentAssignments({ assignments = [], loading }) { const [selected, setSelected] = useState(null); const [file, setFile] = useState(null); const submit = useSubmitHomework(); if (loading) return <div className="student-tab-loading"><span /></div>; return <div className="group-panel student-readonly-panel"><div className="group-panel-head"><div><span>KURS VAZIFALARI</span><h2>Vazifalar</h2></div></div><div className="student-workspace-list">{assignments.map((item) => <article key={item.id}><span className="workspace-list-icon"><ListChecks size={20} /></span><div><strong>{item.title}</strong><p>{item.dueAt ? `Muddat: ${new Intl.DateTimeFormat("uz-UZ", { dateStyle: "medium", timeStyle: "short" }).format(new Date(item.dueAt))}` : "Muddat yo‘q"}</p></div>{item.mySubmission ? <SubmissionStatus initial={item.mySubmission} /> : <Button size="sm" onClick={() => setSelected(item)}>Topshirish</Button>}</article>)}</div><Dialog open={Boolean(selected)} onOpenChange={(open) => { if (!open) { setSelected(null); setFile(null); } }}>{selected ? <DialogContent title={selected.title} description="Topshiriq faylini yuklang (maksimal 25 MB)."><div className="homework-submit-dialog"><p>{selected.description}</p><input type="file" accept={selected.skillKey === "speaking" ? ".pdf,.png,.jpg,.jpeg,.webp,.docx,.mp3,.wav,.m4a,.ogg" : ".pdf,.png,.jpg,.jpeg,.webp,.docx"} onChange={(event) => setFile(event.target.files?.[0] ?? null)} /><Button loading={submit.isPending} disabled={!file} onClick={() => submit.mutateAsync({ assignmentId: selected.id, file, skillKey: selected.skillKey }).then(() => setSelected(null))}>Yuborish</Button></div></DialogContent> : null}</Dialog></div>; }
function SubmissionStatus({ initial }) { const submission = useSubmission(initial.id, { poll: initial.status === "checking" }); const data = submission.data ?? initial; if (data.status === "done") return <span className="grade-pill"><CheckCircle2 size={15} /> {data.overallScore} ball</span>; if (data.status === "error") return <span className="grade-pill grade-pill--error">Tekshiruv xatosi</span>; return <span className="grade-pill grade-pill--checking">Tekshirilmoqda…</span>; }
