export function mapAiResultDto(dto) {
  if (!dto) return null;
  return {
    overallScore: dto.overall_score ?? null, grade: dto.grade ?? "",
    questions: (dto.questions ?? []).map((item) => ({ questionNumber: item.question_number, question: item.question, studentAnswer: item.student_answer, expectedSolution: item.expected_solution, analysis: item.analysis, mistakes: item.mistakes ?? [], errorCategories: item.error_categories ?? [], correctAnswer: item.correct_answer, suggestions: item.suggestions ?? [], difficulty: item.difficulty, score: item.score })),
    summary: dto.summary ? { strengths: dto.summary.strengths ?? [], weaknesses: dto.summary.weaknesses ?? [], topicsToReview: dto.summary.topics_to_review ?? [], recommendations: dto.summary.recommendations ?? [] } : null,
  };
}
export function mapSubmissionDto(dto) { if (!dto) return null; return { id: String(dto.id), assignmentId: String(dto.assignment_id), studentId: String(dto.student_id), studentName: dto.student_name, fileName: dto.file_name, status: dto.status, overallScore: dto.overall_score, grade: dto.grade, error: dto.error || "", isLate: Boolean(dto.is_late), createdAt: dto.created_at, checkedAt: dto.checked_at, result: mapAiResultDto(dto.result) }; }
export function mapAssignmentDto(dto) { return { id: String(dto.id), courseId: String(dto.course_id), courseTitle: dto.course_title, subject: dto.subject, title: dto.title, description: dto.description || "", body: dto.body || "", attachmentName: dto.attachment_name || "", hasAttachment: Boolean(dto.has_attachment), dueAt: dto.due_at, skillKey: dto.skill_key || "", createdAt: dto.created_at, submissionsCount: dto.submissions_count ?? null, mySubmission: mapSubmissionDto(dto.my_submission), submissions: (dto.submissions ?? []).map(mapSubmissionDto), stats: dto.stats ? { studentsCount: dto.stats.students_count, submittedCount: dto.stats.submitted_count, averageScore: dto.stats.avg_score } : null }; }
export function mapAssignmentRequest(form) { const data = new FormData(); data.set("course_id", form.courseId); data.set("title", form.title); data.set("description", form.description || ""); data.set("body", form.body || form.description || ""); if (form.dueAt) data.set("due_at", form.dueAt); if (form.skillKey) data.set("skill_key", form.skillKey); if (form.extraInstructions) data.set("extra_instructions", form.extraInstructions); if (form.file) data.set("attachment", form.file); return data; }
