import { useState } from "react";
import { motion } from "framer-motion";
import { Camera, CheckCircle2, Clock3, Link2, Plus, ShieldCheck, Sparkles, UsersRound, Video } from "lucide-react";
import { Avatar } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent } from "@/components/ui/dialog";
import { useCreateChild, useParentChildren, useParentConsents, useRequestChildLink, useSelectedChild, useSetParentConsent } from "@/modules/parent";
import { LoadingFallback, RouteState } from "@/shared/ui";

const emptyChild = { username: "", password: "", first_name: "", last_name: "" };
const consentKinds = [{ id: "recording", label: "Dars yozuvi", description: "Darsni yozib olishga ruxsat", icon: Video }, { id: "camera", label: "Kamera", description: "Jonli darsda kameradan foydalanish", icon: Camera }, { id: "analytics", label: "Faollik tahlili", description: "Davomat, diqqat va fokus tahlili", icon: Sparkles }];

export function ParentChildrenPage() {
  const childrenQuery = useParentChildren(); const consents = useParentConsents(); const requestLink = useRequestChildLink(); const createChild = useCreateChild(); const setConsent = useSetParentConsent(); const { selectedChild, selectedChildId, selectChild } = useSelectedChild();
  const [linkOpen, setLinkOpen] = useState(false); const [childOpen, setChildOpen] = useState(false); const [inviteCode, setInviteCode] = useState(""); const [child, setChild] = useState(emptyChild); const [formError, setFormError] = useState("");
  async function submitLink(event) { event.preventDefault(); setFormError(""); try { await requestLink.mutateAsync(inviteCode.trim().toUpperCase()); setInviteCode(""); setLinkOpen(false); } catch (error) { setFormError(error.message); } }
  async function submitChild(event) { event.preventDefault(); setFormError(""); try { await createChild.mutateAsync(child); setChild(emptyChild); setChildOpen(false); } catch (error) { setFormError(error.message); } }
  function toggleConsent(kind) { const current = (consents.data ?? []).find((item) => item.studentId === selectedChildId && item.kind === kind); setConsent.mutate({ studentId: selectedChildId, kind, granted: !current?.granted }); }
  if (childrenQuery.isLoading) return <LoadingFallback label="Farzandlar yuklanmoqda" />;
  if (childrenQuery.isError) return <RouteState title="Farzandlar ro‘yxatini yuklab bo‘lmadi" actionLabel="Qayta urinish" onAction={childrenQuery.refetch} />;
  return <div className="portal-page"><div className="portal-page-heading"><div><span className="portal-eyebrow">OILA PROFILI</span><h1>Farzandlarim</h1><p>Biriktirilgan o‘quvchi hisoblari va maxfiylik ruxsatlari.</p></div><div className="heading-actions"><Button variant="secondary" onClick={() => { setFormError(""); setLinkOpen(true); }}><Link2 size={17} /> O‘quvchini ulash</Button><Button onClick={() => { setFormError(""); setChildOpen(true); }}><Plus size={17} /> Bola hisobi</Button></div></div>
    <div className="children-card-grid">{childrenQuery.data.map((item, index) => <motion.button type="button" className={`child-profile-card child-profile-card--button ${selectedChildId === item.id ? "is-selected" : ""}`} key={item.id} onClick={() => selectChild(item.id)} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * 0.05 }}><div className="child-card-status"><CheckCircle2 size={15} /> {selectedChildId === item.id ? "Tanlangan" : "Tasdiqlangan"}</div><Avatar name={item.name} tone={item.avatarTone} size="lg" status="online" /><h2>{item.name}</h2><p>{item.username} · {item.grade}</p><div className="child-stats"><span><CheckCircle2 size={16} /><strong>{item.lessons}</strong><small>dars</small></span><span><Clock3 size={16} /><strong>{item.minutes}</strong><small>daqiqa</small></span></div><div className="child-last"><small>So‘nggi faollik</small><strong>{item.lastActivity}</strong></div></motion.button>)}</div>
    {!childrenQuery.data.length && <div className="portal-empty"><UsersRound size={30} /><h2>Farzand hali ulanmagan</h2><p>O‘quvchi kodini kiriting yoki yangi hisob yarating.</p></div>}
    {selectedChild ? <section className="portal-card consent-panel"><div className="portal-section-head"><div><span>MAXFIYLIK</span><h2>{selectedChild.name} uchun ruxsatlar</h2></div><ShieldCheck size={22} /></div><div className="consent-list">{consentKinds.map((kind) => { const Icon = kind.icon; const granted = (consents.data ?? []).some((item) => item.studentId === selectedChildId && item.kind === kind.id && item.granted); return <button key={kind.id} disabled={consents.isLoading || setConsent.isPending} onClick={() => toggleConsent(kind.id)}><span className="consent-icon"><Icon size={18} /></span><span><strong>{kind.label}</strong><small>{kind.description}</small></span><i className={granted ? "is-active" : ""}>{granted ? "Yoqilgan" : "O‘chiq"}</i></button>; })}</div>{consents.isError ? <div className="form-alert">Ruxsatlarni yuklab bo‘lmadi.</div> : null}</section> : null}
    <Dialog open={linkOpen} onOpenChange={setLinkOpen}>{linkOpen && <DialogContent title="O‘quvchini ulash" description="O‘quvchi profilidagi FK-... taklif kodini kiriting."><form className="dialog-form" onSubmit={submitLink}><label className="field-group"><span>Taklif kodi</span><div className="input-shell"><input autoFocus value={inviteCode} onChange={(event) => setInviteCode(event.target.value)} placeholder="FK-XXXX" required /></div></label>{formError && <div className="form-alert">{formError}</div>}<div className="dialog-actions"><Button type="button" variant="secondary" onClick={() => setLinkOpen(false)}>Bekor</Button><Button type="submit" loading={requestLink.isPending}>So‘rov yuborish</Button></div></form></DialogContent>}</Dialog>
    <Dialog open={childOpen} onOpenChange={setChildOpen}>{childOpen && <DialogContent title="Bola hisobini yaratish" description="Yaratilgan o‘quvchi sizga avtomatik ulanadi."><form className="dialog-form" onSubmit={submitChild}><div className="register-name-grid"><label className="field-group"><span>Ism</span><div className="input-shell"><input value={child.first_name} onChange={(event) => setChild((value) => ({ ...value, first_name: event.target.value }))} required /></div></label><label className="field-group"><span>Familiya</span><div className="input-shell"><input value={child.last_name} onChange={(event) => setChild((value) => ({ ...value, last_name: event.target.value }))} required /></div></label></div><label className="field-group"><span>Login</span><div className="input-shell"><input value={child.username} onChange={(event) => setChild((value) => ({ ...value, username: event.target.value }))} required /></div></label><label className="field-group"><span>Vaqtinchalik parol</span><div className="input-shell"><input type="password" value={child.password} onChange={(event) => setChild((value) => ({ ...value, password: event.target.value }))} minLength={8} required /></div></label>{formError && <div className="form-alert">{formError}</div>}<div className="dialog-actions"><Button type="button" variant="secondary" onClick={() => setChildOpen(false)}>Bekor</Button><Button type="submit" loading={createChild.isPending}>Hisob yaratish</Button></div></form></DialogContent>}</Dialog>
  </div>;
}
